PyTorch is an open-source deep learning framework based on the Python programming language and optimized for deep neural networks

In [1]:
import torch
torch.__version__

'2.14.0'

In [2]:
# using zeros
A=torch.zeros(2,3)
print(A)
# using ones
B=torch.ones(2,3)
print(B)
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)
print(tensor0d)
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d)
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])
print(tensor2d)
# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

# [1, 2, 3] -> 1D tensor (vector)
# [[1, 2], [3, 4]] -> 2D tensor (matrix)
# [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] -> 3D tensor (stack of matrices)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Dimension and shape of matrices

In [44]:
scalar=torch.tensor(8)
print(scalar.ndim)  #to know the number of dimension  scalar have zero dimension dim no of pointer required to access it 1d or 2d
vector=torch.tensor([3,4])  #ndim=1
print(vector.ndim)
vectors=torch.tensor([[3,4],[4,6]])  #ndim=1
print(vectors.ndim)
print(vectors.shape) #to know the shape of matrix

0
1
2
torch.Size([2, 2])


To generate random number

In [17]:
#This creates a 3 × 4 tensor where every number is randomly sampled from a uniform distribution between 0 and 1.
a=torch.rand(size=(3,4))
print(a)
#This also creates a 3 × 4 tensor, but the numbers come from a standard normal distribution (Gaussian distribution). mean=0 std devn=1
b=torch.randn(3,4)
print(b)

tensor([[0.7404, 0.0179, 0.6846, 0.1123],
        [0.8411, 0.4671, 0.8253, 0.0606],
        [0.0618, 0.3313, 0.8386, 0.5533]])
tensor([[ 1.5220,  0.7815,  1.5101,  0.6243],
        [ 0.2353, -0.9816,  0.3733, -0.2917],
        [-0.4785, -0.1003,  0.0409, -0.2560]])


To know the datatype and shape

In [47]:
#to know the datatypes
a=torch.rand(3,4)
print(a)
print(a.dtype)
# assign data type
a=torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
a=torch.tensor([1,2,3], dtype=torch.float64)
a=torch.arange(3,8,dtype=torch.float32)
print(a)
print(a.dtype)
#to change the datatype of a variable
a=a.type(torch.float64)
print(a.dtype)
a=torch.rand(3,4)
print(a.shape)
#to do transpose
a=a.T
print(a.shape)

tensor([[0.6639, 0.3527, 0.5082, 0.1881],
        [0.0672, 0.1166, 0.6677, 0.3921],
        [0.4584, 0.1728, 0.2729, 0.4183]])
torch.float32
tensor([3., 4., 5., 6., 7.])
torch.float32
torch.float64
torch.Size([3, 4])
torch.Size([4, 3])


In [48]:
a=torch.arange(3,10,2,dtype=torch.float32)
print(a)
print(a.dtype)

tensor([3., 5., 7., 9.])
torch.float32


# Matrix Multiplication
1)Treat everything except the last two dims as batch dimensions

2)Last two dims must follow matrix multiplication rules:
A:(,…, , , m, n) @ B:(,…,,, n, p) → result (…, m, p)

3)Batch dimensions must be broadcastable according to PyTorch broadcasting rules

4)Broadcasting rules for batch dimensions:Batch dims must be equal or 1.If not, → RuntimeErroR

In [49]:
import torch
#DIMENSION = (A,B,C,D) OR (C,D)
# Create two 2D tensors
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)
#d=torch.tensor([[[1,2],[3,4]],
               # [[4,5],[5,7]]], dtype=torch.float32)
#print(d.shape)
print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)

# Matrix multiplication
#print(d)
C = torch.matmul(A, B)
print( C)


torch.Size([2, 2])
torch.Size([2, 2])
tensor([[19., 22.],
        [43., 50.]])


In [51]:
import torch
#DIMENSION = (A,B,C,D) OR (C,D)
# Create two 2D tensors
A = torch.tensor([[1, 2,4],
                  [3, 4,5]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8],[4,5]], dtype=torch.float32)

print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)


C = torch.matmul(A, B)  # or A @ B
print( C)
print(C.shape)

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[35., 42.],
        [63., 75.]])
torch.Size([2, 2])


In [6]:
A = torch.tensor([[5, 6],
                  [7, 8],[4,5]], dtype=torch.float32)
B=torch.tensor([[[1,2],[3,4]]], dtype=torch.float32)
print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)


C = torch.matmul(A, B)  # or A @ B
print( C)
print(C.shape)   
# pytorch broadcast 3,2 to 1,3,2  1,2,2

torch.Size([3, 2])
torch.Size([1, 2, 2])
tensor([[[23., 34.],
         [31., 46.],
         [19., 28.]]])
torch.Size([1, 3, 2])


In [57]:
a=torch.tensor([2,3,4])
print(a.shape)
#torch.size([2]) #dimension 1 of size 2

torch.Size([3])


In [7]:
# Vector shape: (2,)
v = torch.tensor([3, 4], dtype=torch.float32)    #SHAPE 1*2      A=3,2   V=2
print(v)
print(v.shape)        #treat(2,) as a column vector
print(A.shape)
print(A)

# Matrix × Vector
result = torch.matmul(A, v)  # mv = matrix-vector                   [3,2]*[2,1]=[3,1]  = SIZE[3]
print("Matrix × Vector =", result)
print(result.shape)


tensor([3., 4.])
torch.Size([2])
torch.Size([3, 2])
tensor([[5., 6.],
        [7., 8.],
        [4., 5.]])
Matrix × Vector = tensor([39., 53., 32.])
torch.Size([3])


In [ ]:
import torch
A = torch.randn(3, 2, 4, 5)
#print(A)  # batch=3, each 2×4
print(A.shape)
v = torch.randn(5)
#print(v)   # 1     # vector of length 4      (3,2,1)
print(v.shape)

C = torch.matmul(A, v)
print(C)
print(C.shape)  # torch.Size([3, 2])      #pytroch removes the extra dimesnion if its was a 1D
#Matrix multiplication = (..., m, n) @ (n,) -> (..., m)


torch.Size([3, 2, 4, 5])
torch.Size([5])
tensor([[[-0.0451, -2.0921, -0.0887,  1.1361],
         [ 1.3731,  2.0303, -0.6892, -2.9680]],

        [[ 1.8675, -1.6996, -2.1812,  1.4274],
         [ 0.3210, -0.6754, -0.8106, -1.8460]],

        [[-0.2640, -2.6869, -0.9396, -0.4094],
         [ 0.5021,  0.2577,  1.6413,  3.0874]]])
torch.Size([3, 2, 4])


In [ ]:
a=torch.randn(size=(2,3,4),dtype=torch.float64)
b=torch.randn(size=(2,4,3),dtype=torch.float64)
#Matrix multiplication = (..., m, n) @ (n,) -> (..., m)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
tensor([[[-2.3960,  1.1126, -0.9410],
         [-0.5125,  1.4893, -2.9673],
         [-2.8169,  0.3329, -1.0410]],

        [[-0.0929,  0.2965, -0.0472],
         [ 0.8745,  0.2426,  0.7976],
         [-5.9326,  2.3166, -4.2773]]], dtype=torch.float64)
torch.Size([2, 3, 3])


In [ ]:
a=torch.randn(size=(2,3,4),dtype=torch.float64)
b=torch.randn(size=(1,4,3),dtype=torch.float64)  #[4,3][4,3]
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 3, 4])
torch.Size([1, 4, 3])
tensor([[[ 1.8605, -1.9550,  0.4742],
         [-1.4224,  1.7079,  0.7190],
         [-2.6652, -0.6100, -0.1762]],

        [[-1.4222,  0.6152,  0.7505],
         [-3.7221,  5.2698,  2.1137],
         [ 1.5860, -1.3572, -0.3795]]], dtype=torch.float64)
torch.Size([2, 3, 3])


In [ ]:
a=torch.randn(size=(2,2,3,4),dtype=torch.float64) 1,2,2,3,4
b=torch.randn(size=(1,1,1,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 2, 3, 4])
torch.Size([1, 1, 1, 4, 3])
tensor([[[[[ 0.8744, -1.2249, -1.6161],
           [ 1.3214, -0.4266, -1.3138],
           [-1.6064,  2.2793, -0.2516]],

          [[ 0.5401, -0.6473, -1.2964],
           [ 1.0953, -0.1567, -1.3391],
           [-1.7345,  2.7652,  0.6834]]],


         [[[ 1.9622, -0.2596, -0.7991],
           [ 1.3884,  0.6733, -1.8978],
           [-2.3669,  2.5092,  1.9356]],

          [[ 1.0825,  1.0145, -2.3334],
           [-0.3481,  0.5173, -0.3274],
           [-0.3388,  0.2225,  0.2260]]]]], dtype=torch.float64)
torch.Size([1, 2, 2, 3, 3])


In [ ]:
a=torch.randn(size=(2,2,2,3,4),dtype=torch.float64)
b=torch.randn(size=(1,1,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 2, 2, 3, 4])
torch.Size([1, 1, 4, 3])
tensor([[[[[ 0.6644,  0.6248, -0.6322],
           [ 2.8884, -0.2129, -5.0342],
           [ 3.1025, -0.3788, -2.0322]],

          [[ 5.3160, -0.8014, -5.4845],
           [-1.5146,  0.3314,  3.7589],
           [-3.7037,  0.8331,  1.4616]]],


         [[[-1.6954,  0.5860,  4.9583],
           [-2.1589, -0.0770,  1.0341],
           [-1.3761,  0.7742,  1.6660]],

          [[-0.7937,  0.6355,  2.7374],
           [-1.0873, -0.8680, -8.0788],
           [-5.1599,  2.4095,  6.8915]]]],



        [[[[-0.8291, -0.0503,  1.0935],
           [ 2.1544, -1.0749, -0.8600],
           [ 2.0290, -1.3999, -6.6244]],

          [[-2.0489,  1.0786,  3.0323],
           [-0.3652,  0.0870,  1.0091],
           [ 0.6318,  0.1489, -1.9879]]],


         [[[ 1.7936, -0.8157, -3.8455],
           [-2.4540, -1.1263, -6.6198],
           [ 0.5252,  0.2571,  1.0165]],

          [[-1.4231, -0.0737, -1.4322],
           [-2.5718,  0.8434,  4.6919],
     

In [ ]:
a=torch.randn(size=(2,2,1,3,4),dtype=torch.float64)
b=torch.randn(size=(2,2,3,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
#last 2 dimensions = matrix dimensions
#all earlier dimensions = batch dimensions

torch.Size([2, 2, 1, 3, 4])
torch.Size([2, 2, 3, 4, 3])
tensor([[[[[-0.0738, -0.1702, -0.1339],
           [-0.1943, -1.1288,  0.4024],
           [ 1.6758, -0.7384,  0.1784]],

          [[ 0.0995,  0.0264, -0.1214],
           [ 3.5452,  0.2453,  2.1586],
           [ 0.4877,  0.0184, -1.0703]],

          [[ 0.1901,  0.2469,  0.1972],
           [ 0.6269, -5.7304, -0.1859],
           [-0.8412,  2.4787, -1.0518]]],


         [[[-0.5440, -1.3119,  3.1510],
           [ 1.1740, -0.4541, -1.8428],
           [-0.0203,  1.4150,  1.3843]],

          [[ 0.3649,  1.5670,  2.4300],
           [ 0.8615, -1.5035,  1.4949],
           [-1.6981,  0.1674, -1.7744]],

          [[ 2.0226,  0.3559,  0.2224],
           [ 2.3670,  1.5909,  1.9693],
           [-1.3115, -0.9630, -0.7713]]]],



        [[[[-0.9077,  0.7513,  0.4942],
           [ 1.5841,  1.8815, -2.5958],
           [ 0.3855,  0.7772,  0.0185]],

          [[-0.4069, -0.4784,  1.6032],
           [ 0.8734, -1.6068, -2.8979],
    

In [ ]:
a=torch.randn(size=(2,2,2,3,4),dtype=torch.float64)
b=torch.randn(size=(2,2,1,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
#last 2 dimensions = matrix dimensions
#all earlier dimensions = batch dimensions

torch.Size([2, 2, 2, 3, 4])
torch.Size([2, 2, 1, 4, 3])
tensor([[[[[ 1.7181, -0.4381,  0.1916],
           [ 1.2637,  0.9717,  0.7484],
           [ 1.1471,  1.0727, -0.4436]],

          [[-0.2756, -1.0974, -0.6511],
           [ 1.4351, -0.1903, -0.6824],
           [-2.3512,  0.2845, -1.3762]]],


         [[[ 1.7422, -0.0933, -2.3264],
           [ 1.7228,  1.9757, -4.5967],
           [ 3.9406, -4.7191, -3.0803]],

          [[ 0.0116,  0.4161, -0.0808],
           [-0.5681,  2.7925,  0.1090],
           [-0.3114,  0.1643, -1.5492]]]],



        [[[[ 0.5975, -0.0740, -1.4755],
           [-1.2321, -2.3620,  1.7822],
           [-0.6471, -0.3086, -0.7714]],

          [[ 1.0410,  1.9425,  0.5986],
           [ 1.5363, -0.1794, -2.1063],
           [-1.3008, -2.9228,  0.0203]]],


         [[[-3.9003,  2.4007,  2.5105],
           [ 0.2651, -2.5093, -4.8133],
           [-4.4305,  2.0005,  1.0388]],

          [[ 0.6393, -0.1955, -0.3850],
           [-9.1704,  2.2291, -3.4455],
  

# Dimension reduction

In [50]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)  # shape (2, 3)

# Sum over all elements → scalar
print(torch.sum(x))  # shape: ()

# Sum over rows (dim=0) → keeps columns and do summation columns wise
print(torch.sum(x, dim=0))  # shape: (3,)

# Sum over columns (dim=1) → keeps rows
print(torch.sum(x, dim=1))  # shape: (2,)


tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


In [73]:
y1 = torch.randn(2, 1, 3, 1)  # shape: (2, 1, 3, 1)    [[1][2][3]]
print(y1)
print(y1.shape)
y=torch.randn(2,1,1,1,1,1,1,1,1,3,2)
y_squeezed = torch.squeeze(y)  # removes all size-1 dims
print(y_squeezed.shape)  # (2, 3)

# Remove only a specific axis
print(torch.squeeze(y1, dim=0).shape)  # (2, 3, 1)    #Remove dimension 0 IF its size is 1. Otherwise, leave it unchanged


tensor([[[[-0.7940],
          [-0.0163],
          [-0.1557]]],


        [[[-1.0860],
          [-1.9272],
          [ 0.0598]]]])
torch.Size([2, 1, 3, 1])
torch.Size([2, 3, 2])
torch.Size([2, 1, 3, 1])


In [67]:
import torch
# Create sample tensor
x = torch.arange(12).reshape(2, 2, 3)
#print("Original shape:", x.shape)
#print(x, "\n")


# Flattening / reshaping
a=torch.flatten(x)
#print(a)
print("torch.flatten all:", a.shape)  # (12,)
print("torch.flatten from dim=1:", torch.flatten(x, start_dim=1).shape)  # (2, 6)
#print("reshape alternative:", x.reshape(1, 12).shape)  # (1, 12)




torch.flatten all: torch.Size([12])
torch.flatten from dim=1: torch.Size([2, 6])


# limiting the numbers of gpu

In [74]:
import os

# Only allow GPU 0 (the first GPU) to be visible
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import torch

print("Available GPUs:", torch.cuda.device_count())
print("Using device:", torch.cuda.current_device())

Available GPUs: 0


AssertionError: Torch not compiled with CUDA enabled

# cpu to gpu and gpu to cpu

In [1]:
import torch
import torch.nn as nn

# Simple model
model = nn.Linear(10, 5)  # Initially on CPU
print("Initial device:", next(model.parameters()).device)   #“Get the first parameter of the model, and tell me which device it’s on.”

# ---- Move model to GPU (if available) ----
if torch.cuda.is_available():
    model = model.to("cuda")
print("After moving to GPU:", next(model.parameters()).device)

# ---- Create a random input on GPU and run forward pass ----
if torch.cuda.is_available():
    x = torch.randn(4, 10, device="cuda")  # input on GPU
else:
    x = torch.randn(4, 10)
output = model(x)
print("Output device:", output.device)

# ---- Move model back to CPU ----
model = model.to("cpu")
print("After moving back to CPU:", next(model.parameters()).device)

# ---- Input also must be on CPU when model is on CPU ----
x_cpu = x.cpu()
output_cpu = model(x_cpu)
print("Output device after moving back to CPU:", output_cpu.device)


Initial device: cpu
After moving to GPU: cuda:0
Output device: cuda:0
After moving back to CPU: cpu
Output device after moving back to CPU: cpu
