PyTorch is an open-source deep learning framework based on the Python programming language and optimized for deep neural networks

In [53]:
import torch
torch.__version__

'2.14.0'

In [54]:
# using zeros
A=torch.zeros(2,3)
print(A)
# using ones
B=torch.ones(2,3)
print(B)
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)
print(tensor0d)
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d)
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])
print(tensor2d)
# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [55]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

# [1, 2, 3] -> 1D tensor (vector)
# [[1, 2], [3, 4]] -> 2D tensor (matrix)
# [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] -> 3D tensor (stack of matrices)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Dimension and shape of matrices

In [56]:
scalar=torch.tensor(8)
print(scalar.ndim)  #to know the number of dimension  scalar have zero dimension dim no of pointer required to access it 1d or 2d
vector=torch.tensor([3,4])  #ndim=1
print(vector.ndim)
vectors=torch.tensor([[3,4],[4,6]])  #ndim=1
print(vectors.ndim)
print(vectors.shape) #to know the shape of matrix

0
1
2
torch.Size([2, 2])


To generate random number

In [57]:
#This creates a 3 × 4 tensor where every number is randomly sampled from a uniform distribution between 0 and 1.
a=torch.rand(size=(3,4))
print(a)
#This also creates a 3 × 4 tensor, but the numbers come from a standard normal distribution (Gaussian distribution). mean=0 std devn=1
b=torch.randn(3,4)
print(b)

tensor([[0.4968, 0.5514, 0.0615, 0.3503],
        [0.5465, 0.5931, 0.8973, 0.0044],
        [0.8733, 0.2039, 0.2973, 0.1704]])
tensor([[ 1.9111,  0.2474, -0.2195, -0.4414],
        [ 0.1714, -0.2993,  1.0481,  0.9464],
        [-0.2818, -0.3298,  0.7954, -0.2959]])


To know the datatype and shape

In [58]:
#to know the datatypes
a=torch.rand(3,4)
print(a)
print(a.dtype)
# assign data type
a=torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
a=torch.tensor([1,2,3], dtype=torch.float64)
a=torch.arange(3,8,dtype=torch.float32)
print(a)
print(a.dtype)
#to change the datatype of a variable
a=a.type(torch.float64)
print(a.dtype)
a=torch.rand(3,4)
print(a.shape)
#to do transpose
a=a.T
print(a.shape)

tensor([[0.9069, 0.5254, 0.6100, 0.7309],
        [0.2808, 0.0879, 0.8875, 0.2458],
        [0.6774, 0.1951, 0.0849, 0.6104]])
torch.float32
tensor([3., 4., 5., 6., 7.])
torch.float32
torch.float64
torch.Size([3, 4])
torch.Size([4, 3])


In [59]:
a=torch.arange(3,10,2,dtype=torch.float32)
print(a)
print(a.dtype)

tensor([3., 5., 7., 9.])
torch.float32


# Matrix Multiplication
1)Treat everything except the last two dims as batch dimensions

2)Last two dims must follow matrix multiplication rules:
A:(,…, , , m, n) @ B:(,…,,, n, p) → result (…, m, p)

3)Batch dimensions must be broadcastable according to PyTorch broadcasting rules

4)Broadcasting rules for batch dimensions:Batch dims must be equal or 1.If not, → RuntimeErroR

In [60]:
import torch
#DIMENSION = (A,B,C,D) OR (C,D)
# Create two 2D tensors
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)
#d=torch.tensor([[[1,2],[3,4]],
               # [[4,5],[5,7]]], dtype=torch.float32)
#print(d.shape)
print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)

# Matrix multiplication
#print(d)
C = torch.matmul(A, B)
print( C)


torch.Size([2, 2])
torch.Size([2, 2])
tensor([[19., 22.],
        [43., 50.]])


In [61]:
import torch
#DIMENSION = (A,B,C,D) OR (C,D)
# Create two 2D tensors
A = torch.tensor([[1, 2,4],
                  [3, 4,5]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8],[4,5]], dtype=torch.float32)

print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)


C = torch.matmul(A, B)  # or A @ B
print( C)
print(C.shape)

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[35., 42.],
        [63., 75.]])
torch.Size([2, 2])


In [62]:
A = torch.tensor([[5, 6],
                  [7, 8],[4,5]], dtype=torch.float32)
B=torch.tensor([[[1,2],[3,4]]], dtype=torch.float32)
print(A.shape)   #(B,r,c) where B= BATCHES , r=row, c=column
print(B.shape)


C = torch.matmul(A, B)  # or A @ B
print( C)
print(C.shape)   
# pytorch broadcast 3,2 to 1,3,2  1,2,2

torch.Size([3, 2])
torch.Size([1, 2, 2])
tensor([[[23., 34.],
         [31., 46.],
         [19., 28.]]])
torch.Size([1, 3, 2])


In [63]:
a=torch.tensor([2,3,4])
print(a.shape)
#torch.size([2]) #dimension 1 of size 2

torch.Size([3])


In [64]:
# Vector shape: (2,)
v = torch.tensor([3, 4], dtype=torch.float32)    #SHAPE 1*2      A=3,2   V=2
print(v)
print(v.shape)        #treat(2,) as a column vector
print(A.shape)
print(A)

# Matrix × Vector
result = torch.matmul(A, v)  # mv = matrix-vector                   [3,2]*[2,1]=[3,1]  = SIZE[3]
print("Matrix × Vector =", result)
print(result.shape)


tensor([3., 4.])
torch.Size([2])
torch.Size([3, 2])
tensor([[5., 6.],
        [7., 8.],
        [4., 5.]])
Matrix × Vector = tensor([39., 53., 32.])
torch.Size([3])


In [65]:
import torch
A = torch.randn(3, 2, 4, 5)
#print(A)  # batch=3, each 2×4
print(A.shape)
v = torch.randn(5)
#print(v)   # 1     # vector of length 4      (3,2,1)
print(v.shape)

C = torch.matmul(A, v)
print(C)
print(C.shape)  # torch.Size([3, 2])      #pytroch removes the extra dimesnion if its was a 1D
#Matrix multiplication = (..., m, n) @ (n,) -> (..., m)


torch.Size([3, 2, 4, 5])
torch.Size([5])
tensor([[[-3.1775, -0.8148,  1.8339,  0.2968],
         [-0.9095, -0.0930, -0.5086, -0.3298]],

        [[-1.4005,  1.2892,  0.8003,  0.6393],
         [-0.3930, -0.3672, -0.5283, -0.4760]],

        [[-0.0361,  2.3681,  3.0595,  1.2651],
         [-1.7356, -2.0397, -1.7034, -1.2811]]])
torch.Size([3, 2, 4])


In [66]:
a=torch.randn(size=(2,3,4),dtype=torch.float64)
b=torch.randn(size=(2,4,3),dtype=torch.float64)
#Matrix multiplication = (..., m, n) @ (n,) -> (..., m)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
tensor([[[ 2.6610,  1.1620,  1.5256],
         [ 0.3219,  1.8615, -0.1597],
         [-0.7347,  0.0238,  0.5911]],

        [[-0.9929,  1.8419,  0.6225],
         [-0.0838, -3.5296,  0.1384],
         [-2.3758,  3.7940,  0.2839]]], dtype=torch.float64)
torch.Size([2, 3, 3])


In [67]:
a=torch.randn(size=(2,3,4),dtype=torch.float64)
b=torch.randn(size=(1,4,3),dtype=torch.float64)  #[4,3][4,3]
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 3, 4])
torch.Size([1, 4, 3])
tensor([[[-0.0397, -0.8797,  1.7785],
         [ 0.4260,  0.4032,  0.1515],
         [-0.7766,  1.0862,  0.4296]],

        [[-1.1689,  2.7850, -0.3303],
         [-0.4226,  1.7143,  0.5776],
         [ 3.6315, -6.4044, -3.1423]]], dtype=torch.float64)
torch.Size([2, 3, 3])


In [72]:
a=torch.randn(size=(2,2,3,4),dtype=torch.float64) 
#1,2,2,3,4
b=torch.randn(size=(1,1,1,4,3),dtype=torch.float64)  
#it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 2, 3, 4])
torch.Size([1, 1, 1, 4, 3])
tensor([[[[[ 2.6232e-02,  2.8175e-01,  7.5083e-01],
           [-1.7400e-01,  1.3889e+00,  3.3555e+00],
           [ 1.7438e-01, -3.6730e+00, -1.4480e+00]],

          [[-7.1618e-01,  6.1165e+00,  2.7623e+00],
           [-2.0457e-02,  1.3760e+00, -3.1241e+00],
           [-2.9193e-03,  7.9770e-01, -7.1686e-01]]],


         [[[ 4.4624e-01, -2.6945e+00,  4.9135e-01],
           [ 5.0278e-01, -3.3726e+00,  1.8141e+00],
           [-1.5589e-01,  1.3792e+00,  2.3465e-01]],

          [[ 4.7250e-01, -4.5535e+00, -3.8705e+00],
           [-1.1627e-01,  1.1497e-01,  3.1329e-01],
           [ 6.5071e-02, -3.0021e-01, -3.9872e+00]]]]], dtype=torch.float64)
torch.Size([1, 2, 2, 3, 3])


In [73]:
a=torch.randn(size=(2,2,2,3,4),dtype=torch.float64)
b=torch.randn(size=(1,1,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)

torch.Size([2, 2, 2, 3, 4])
torch.Size([1, 1, 4, 3])
tensor([[[[[-0.1220, -0.8581, -0.0301],
           [ 2.3379, -1.4622, -3.4764],
           [-1.0571,  0.1554, -1.0407]],

          [[-0.5059, -0.6212,  0.8908],
           [ 1.0745,  0.5753, -2.5863],
           [ 2.0720, -0.8283, -1.0439]]],


         [[[-1.9367,  1.5199,  3.0599],
           [ 1.3115, -0.2696, -0.1989],
           [ 1.9949, -0.3451, -4.1633]],

          [[ 1.1818, -0.9105, -0.1645],
           [ 0.2542, -1.0207,  1.2840],
           [-0.1901,  1.8608, -1.2390]]]],



        [[[[ 1.0741, -0.0939, -1.6981],
           [ 0.2755, -0.5194, -0.1005],
           [-0.2766, -0.8760, -0.5279]],

          [[-2.0217,  1.7650,  1.9199],
           [-0.2703, -1.4898,  1.2413],
           [ 2.7124, -1.0866, -3.2114]]],


         [[[-0.9584, -0.3512,  1.7566],
           [ 0.2774, -0.2710, -1.7786],
           [ 1.2690, -1.3002, -0.7630]],

          [[-3.2024,  0.5376,  3.6171],
           [-1.9491, -0.0772,  2.7244],
     

In [74]:
a=torch.randn(size=(2,2,1,3,4),dtype=torch.float64)
b=torch.randn(size=(2,2,3,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
#last 2 dimensions = matrix dimensions
#all earlier dimensions = batch dimensions

torch.Size([2, 2, 1, 3, 4])
torch.Size([2, 2, 3, 4, 3])
tensor([[[[[ 1.4338,  0.9090, -0.7024],
           [ 1.6434,  0.3049, -1.4755],
           [-3.0697,  0.1903, -0.5085]],

          [[ 0.2416,  0.4007, -2.6073],
           [ 1.6411, -1.2620, -3.4202],
           [-1.5847, -1.8031, -1.4367]],

          [[ 1.0472, -0.9487, -0.2400],
           [ 1.5148, -0.8587, -1.7037],
           [-0.2528, -1.3429, -2.9470]]],


         [[[ 0.2679, -1.5180,  0.6510],
           [-0.3006, -0.5776, -0.7519],
           [ 0.8879,  4.5658, -0.6704]],

          [[-0.9145,  3.0737, -4.4263],
           [-0.1755, -0.5042, -0.1525],
           [ 1.5693,  1.8496,  0.3112]],

          [[ 0.1493,  0.5956, -0.4533],
           [ 1.0812, -0.1570, -0.3678],
           [-1.3848,  0.1291, -0.9039]]]],



        [[[[-3.5080, -0.5742, -2.9568],
           [ 0.1289,  0.7361,  0.3280],
           [-3.0815, -2.1915, -3.1014]],

          [[ 1.1546,  0.5068, -1.5698],
           [ 0.0066, -0.4624,  0.0970],
    

In [75]:
a=torch.randn(size=(2,2,2,3,4),dtype=torch.float64)
b=torch.randn(size=(2,2,1,4,3),dtype=torch.float64)  #it will try to change smaller dimension into larger dimension, then do broadcasting
print(a.shape)
print(b.shape)
c=torch.matmul(a,b)
print(c)
print(c.shape)
#Matrix multiplication = (..., m, n) @ (n, p) -> (..., m, p)
#last 2 dimensions = matrix dimensions
#all earlier dimensions = batch dimensions

torch.Size([2, 2, 2, 3, 4])
torch.Size([2, 2, 1, 4, 3])
tensor([[[[[-0.9213,  1.0968, -3.1144],
           [ 1.6690,  0.2807, -4.8515],
           [ 1.6690,  2.3504,  0.8453]],

          [[-0.7857, -0.5396, -4.5264],
           [ 0.5059, -0.1733,  1.6938],
           [ 2.1632,  0.5437, -2.5194]]],


         [[[-0.3505, -0.0316,  1.0314],
           [ 0.5488, -0.6398,  0.9478],
           [-3.9230,  1.1954, -0.0648]],

          [[-0.1630, -0.5464,  2.5235],
           [-2.1934, -2.3678,  0.0700],
           [-0.9921, -1.5327,  1.9240]]]],



        [[[[ 0.0357,  0.1182, -0.1394],
           [ 1.2265, -0.4287, -1.7012],
           [-4.9363,  3.0337,  3.0228]],

          [[ 4.0039, -2.0758, -2.5068],
           [-4.3909,  2.5913,  2.1835],
           [ 1.8404, -1.1223, -1.0931]]],


         [[[ 1.8912,  2.6928, -3.3513],
           [ 1.5877,  4.6075, -1.4388],
           [ 1.5936,  3.1293, -2.7205]],

          [[ 1.0608, -3.8662, -1.4539],
           [-1.8977, -2.6999,  1.7772],
  

# Dimension reduction

In [69]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)  # shape (2, 3)

# Sum over all elements → scalar
print(torch.sum(x))  # shape: ()

# Sum over rows (dim=0) → keeps columns and do summation columns wise
print(torch.sum(x, dim=0))  # shape: (3,)

# Sum over columns (dim=1) → keeps rows
print(torch.sum(x, dim=1))  # shape: (2,)


tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


In [79]:
y1 = torch.randn(2, 1, 3, 1)  # shape: (2, 1, 3, 1)    [[1][2][3]]
print(y1)
print(y1.shape)
y=torch.randn(2,1,1,1,1,1,1,1,1,3,2)
y_squeezed = torch.squeeze(y)  # removes all size-1 dims
print(y_squeezed.shape)  # (2, 3)

# Remove only a specific axis
print(torch.squeeze(y1, dim=0).shape)  # (2, 3, 1)    #Remove dimension 0 IF its size is 1. Otherwise, leave it unchanged


tensor([[[[-0.6754],
          [-0.7621],
          [-0.2155]]],


        [[[ 0.4784],
          [-0.5616],
          [-0.1098]]]])
torch.Size([2, 1, 3, 1])
torch.Size([2, 3, 2])
torch.Size([2, 1, 3, 1])


In [78]:
import torch
# Create sample tensor
x = torch.arange(12).reshape(2, 2, 3)
#print("Original shape:", x.shape)
#print(x, "\n")


# Flattening / reshaping
a=torch.flatten(x)
#print(a)
print("torch.flatten all:", a.shape)  # (12,)
print("torch.flatten from dim=1:", torch.flatten(x, start_dim=1).shape)  # (2, 6)
#print("reshape alternative:", x.reshape(1, 12).shape)  # (1, 12)


torch.flatten all: torch.Size([12])
torch.flatten from dim=1: torch.Size([2, 6])


# limiting the numbers of gpu

In [77]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("CUDA GPU count:", torch.cuda.device_count())
print("MPS available:", torch.backends.mps.is_available())

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("Using device:", device)

CUDA available: False
CUDA GPU count: 0
MPS available: True
Using device: mps


# cpu to gpu and gpu to cpu

In [76]:
import torch
import torch.nn as nn

# Simple model
model = nn.Linear(10, 5)  # Initially on CPU
print("Initial device:", next(model.parameters()).device)   #“Get the first parameter of the model, and tell me which device it’s on.”

# ---- Move model to GPU (if available) ----
if torch.cuda.is_available():
    model = model.to("cuda")
print("After moving to GPU:", next(model.parameters()).device)

# ---- Create a random input on GPU and run forward pass ----
if torch.cuda.is_available():
    x = torch.randn(4, 10, device="cuda")  # input on GPU
else:
    x = torch.randn(4, 10)
output = model(x)
print("Output device:", output.device)

# ---- Move model back to CPU ----
model = model.to("cpu")
print("After moving back to CPU:", next(model.parameters()).device)

# ---- Input also must be on CPU when model is on CPU ----
x_cpu = x.cpu()
output_cpu = model(x_cpu)
print("Output device after moving back to CPU:", output_cpu.device)


Initial device: cpu
After moving to GPU: cpu
Output device: cpu
After moving back to CPU: cpu
Output device after moving back to CPU: cpu
