Question 1: Given a $12 \times 12$ matrix generated by np.arange and then reshaped, use slicing and striding to:
1. Extract a sub-matrix containing every 3rd row and every 4th column.
2. Calculate the sum of the elements in this sub-matrix along axis=1.
3. Reshape the resulting 1D sum array into a column vector.

Question 2: You have an array $A$ of shape $(5, 2)$ representing the coordinates of 5 points in 2D space. Each coordinate will be represented as (x,y). Use broadcasting to create a $5 \times 5$ distance matrix where the element at $[i, j]$ is the squared Euclidean distance between point $i$ and point $j$.
  $$d_{ij}^2 = (x_i - x_j)^2 + (y_i - y_j)^2$$
- Hint: The shape of the subtraction should be $(5, 1, 2) - (1, 5, 2)$

Question 3:  One Hot Encoding is a "famous technique" used in the Machine Learning projects. 
1. Task : Given an array of labels [0, 2, 1, 0, 1], convert it into a "One-Hot" matrix.
2. Requirements: Create a matrix of shape (num_labels, num_classes) where a 1 is placed in the column corresponding to the label and 0 elsewhere.

Expected Output: One-Hot Matrix

Based on the labels `[0, 2, 1, 0, 1]` and `num_classes = 3`, the generated NumPy array `one_hot` will be a 2D array of floats.
- Class 0 : [1., 0., 0.]
- Class 1 : [0., 1., 0.]
- Class 2 : [0., 0., 1.]
1. Console Print Output
If you print the result in Python, it will look like this:

```python
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Question 4: You are given an RGB image "baboon.png" (taken from Set 14 dataset : https://www.kaggle.com/datasets/ll01dm/set-5-14-super-resolution-dataset) which is a multidimensional array of shape (Height, Width, 3) . Here 3 represents the number of channels which in our case now is RGB. 

1. Read the image using `plt.imread` or `imageio.imread`
2. Convert the image to a floating-point data type (`np.float32`) to allow for decimal calculations.
3. Perform Global Min Max Normalization
 $$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

* **$x$**: The original pixel intensity.
* **$x_{min}$**: The minimum intensity found in the image array.
* **$x_{max}$**: The maximum intensity found in the image array.
* **$x_{norm}$**: The resulting floating-point value, where $0.0$ represents the darkest point and $1.0$ represents the brightest.

4. Plot the original and the normalized image side by side
- NOTE : Calculate $x_{min}$ and $x_{max}$ globally across all channels

Question 5: We want to highlight the high intensity red regions and leave the rest of the image as grayscale. The output should highlight the baboon's nose.

1. Use the normalized image created in the previous question
2. Identify those pixels where the Red channel instensity is greater than some **${\lambda}$** (Remember for the normalized image the pixel values range from 0.0 to 1.0). For these pixels keep the original colour.
3. Convert the rest of the pixels to grayscale by setting the R, G, B values to the average of the three original channels.
4. Display the result.

Hint
* Construct the grayscale image by averaging across all R, G and B channels.
* Create a boolean mask 2D array based on the Red channel alone by thresholding
* Apply the grayscale value to all three channels where the mask is True.

Question 6: Write a Python program using the NumPy library to perform the following matrix operations:

1. Create two 3×3 matrices A and B with random integer values.

2. Compute and display the sum and difference of matrices A and B.

3. Perform matrix multiplication of A and B.

4. Find and display the transpose of matrix A.

5. Compute the determinant of matrix A.

6. Check whether matrix A is invertible. If it is invertible, compute and display its inverse.

7. Calculate and display the eigenvalues and eigenvectors of matrix A.

Display all matrices and results clearly using appropriate NumPy functions.

Question 7: Write a Python program using NumPy to perform the following operations:

1. Create a 1-dimensional NumPy array of 12 consecutive integers (from 1 to 12). Reshape this array into a 3×4 matrix (Matrix A).

2. Create another 3×4 matrix (Matrix B) with random integers between 10 and 20. Concatenate the two matrices (A and B) vertically and horizontally, and display the results.

3. Stack the two matrices (A and B) along a new third axis using np.stack. Display the resulting 3-dimensional array.

4. Split the vertically concatenated matrix into three equal parts vertically.

5. Split the horizontally concatenated matrix into two equal parts horizontally.

6. Display all the resulting arrays.

Question 8: Write a Python program to generate a collection of random points inside the unit cube defined by 
0 ≤ 𝑥 ≤ 1,  0≤y≤1, and 0≤z≤1. Use these points to create a 3D scatter plot that visualizes the interior of the unit cube. Use appropriate Python libraries such as NumPy for random point generation and Matplotlib for 3D plotting. Label the axes and ensure the cube boundaries are properly represented.

Question 9: Write a Python program using NumPy to perform linear and polynomial least squares fitting on a dataset stored in a CSV file.

The program should perform the following tasks:

1. Load the dataset: Use np.loadtxt() to read a CSV file (e.g., Salary_Data.csv) containing two columns: x (independent variable) and y (dependent variable).

2. Linear Least Squares Fit: Compute the best-fit line y=mx+c using np.linalg.lstsq(), where x: Years of Experience, y: Salary

3. Display the slope (m) and intercept (c). Calculate and display the residuals.

4. Polynomial Fit: Fit a quadratic polynomial (degree 2) to the same data using np.polyfit().

5. Display the polynomial coefficients. Calculate and display the residuals.

6. Calculate the mean and standard deviation of residuals for both linear and polynomial fits.

7. Plot the original data points. Plot the linear fit and polynomial fit on the same graph with appropriate labels, colors, and a legend.

8. Create a plot for residuals to compare the residuals of the linear and polynomial models. Include a horizontal line at zero to visualize deviations.